#!/usr/bin/env python3
"""Seed L20 specs for 13 missing March 2026 posts. One-shot helper."""
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "_data" / "l20_covers"

# Each entry is keyed by (date, slug). Hand-curated from post excerpts.
SPECS = [
    (
        "2026-03-02",
        "Tech_Security_Weekly_Digest_Ransomware_AI_Agent",
        "Weekly digest 2026-03-02: ransomware, BYOVD EDR, SK Shieldus zero-trust report",
        {
            "tag": "RANSOMWARE",
            "theme": "red",
            "visual": "ransomware_lock",
            "headline": "Ransomware-as-a-Service Surge",
            "subheadline": "Affiliate-driven ransomware operations expand to commodity malware payloads",
            "kpi_value": "RAN",
            "kpi_label": "AFFIL",
            "kpi_sub": "extort",
            "action": "ISOLATE + ROTATE KEYS + IR DRILL",
        },
        {
            "tag": "BYOVD EDR",
            "theme": "amber",
            "visual": "code_injection",
            "headline": "BYOVD Driver Sideload",
            "subheadline": "Vulnerable-driver families sideload to disable EDR telemetry",
            "kpi_value": "BYO",
            "kpi_label": "DRIVER",
            "kpi_sub": "killbit",
        },
        {
            "tag": "ZERO TRUST",
            "theme": "blue",
            "visual": "hub_spoke",
            "headline": "SK Shieldus Zero Trust",
            "subheadline": "SK Shieldus February brief - zero trust visibility and reference architecture",
            "kpi_value": "ZTA",
            "kpi_label": "SHIELD",
            "kpi_sub": "feb-rpt",
        },
    ),
    (
        "2026-03-04",
        "Tech_Security_Weekly_Digest_AI_Ransomware_Bitcoin",
        "Weekly digest 2026-03-04: JWT signing key leak, ransomware DNS exfil, cloud exposure",
        {
            "tag": "JWT KEY LEAK",
            "theme": "red",
            "visual": "cve_chain",
            "headline": "JWT Signing Key Leak",
            "subheadline": "Leaked JWT signing key collapses authentication trust boundary",
            "kpi_value": "JWT",
            "kpi_label": "KEY",
            "kpi_sub": "rotate",
            "action": "ROTATE JWT KEYS + INVALIDATE TOKENS",
        },
        {
            "tag": "RANSOMWARE",
            "theme": "amber",
            "visual": "ransomware_lock",
            "headline": "DNS Tunnel Ransomware",
            "subheadline": "Ransomware crews chain DNS tunnels to stage data theft pre-encryption",
            "kpi_value": "DNS",
            "kpi_label": "TUNNEL",
            "kpi_sub": "ransom",
        },
        {
            "tag": "CLOUD EXPOSE",
            "theme": "blue",
            "visual": "container_escape",
            "headline": "Cloud Exposure Surge",
            "subheadline": "Public cloud storage misconfigurations expose customer datasets at scale",
            "kpi_value": "S3",
            "kpi_label": "OPEN",
            "kpi_sub": "buckets",
        },
    ),
    (
        "2026-03-05",
        "Tech_Security_Weekly_Digest_iOS_Exploit_Hacktivist_DDoS",
        "Weekly digest 2026-03-05: Google GTIG 23 zero-days, iOS exploit chain, hacktivist DDoS",
        {
            "tag": "GTIG 0-DAY",
            "theme": "red",
            "visual": "cve_chain",
            "headline": "Google GTIG 23 Zero-Days",
            "subheadline": "Google GTIG report tracks 23 zero-day exploits actively in the wild",
            "kpi_value": "23",
            "kpi_label": "0DAY",
            "kpi_sub": "GTIG",
            "action": "PATCH BROWSER + KERNEL + MOBILE CHAINS",
        },
        {
            "tag": "IOS EXPLOIT",
            "theme": "amber",
            "visual": "code_injection",
            "headline": "iOS Exploit Chain Active",
            "subheadline": "Multi-stage iOS exploit chain delivers spyware via WebKit + kernel pivot",
            "kpi_value": "iOS",
            "kpi_label": "CHAIN",
            "kpi_sub": "spyware",
        },
        {
            "tag": "DDoS",
            "theme": "blue",
            "visual": "hub_spoke",
            "headline": "Hacktivist DDoS Surge",
            "subheadline": "Geopolitical hacktivist groups launch coordinated DDoS across 16 nations",
            "kpi_value": "16",
            "kpi_label": "TARGET",
            "kpi_sub": "DDoS",
        },
    ),
    (
        "2026-03-06",
        "Tech_Security_Weekly_Digest_Security_Threat_AI_AWS",
        "Weekly digest 2026-03-06: CVE-2026-20122 active, Europol 64K AitM takedown, Cisco FMC",
        {
            "tag": "CVE 20122",
            "theme": "red",
            "visual": "cve_chain",
            "headline": "CVE-2026-20122 In The Wild",
            "subheadline": "CVE-2026-20122 active exploitation confirmed - urgent patch required",
            "kpi_value": "RCE",
            "kpi_label": "20122",
            "kpi_sub": "active",
            "action": "PATCH NOW + AUDIT INGRESS LOG",
        },
        {
            "tag": "AitM TAKEDOWN",
            "theme": "amber",
            "visual": "data_exfil",
            "headline": "Europol 64K AitM Bust",
            "subheadline": "Europol-led action dismantles 64000-account AitM phishing operation",
            "kpi_value": "64K",
            "kpi_label": "AitM",
            "kpi_sub": "phish",
        },
        {
            "tag": "CISCO FMC",
            "theme": "blue",
            "visual": "code_injection",
            "headline": "Cisco FMC Privilege Bug",
            "subheadline": "Cisco Firepower Management Center vulnerability enables local privilege escalation",
            "kpi_value": "FMC",
            "kpi_label": "LPE",
            "kpi_sub": "Cisco",
        },
    ),
    (
        "2026-03-07",
        "LLM_Security_Practical_Guide_Prompt_Injection_RAG_MCP",
        "LLM security guide 2026: prompt injection, RAG poisoning, MCP tool poisoning",
        {
            "tag": "PROMPT INJECT",
            "theme": "red",
            "visual": "ai_agent_funnel",
            "headline": "LLM Prompt Injection",
            "subheadline": "Direct and indirect prompt injection defenses across LLM service surface",
            "kpi_value": "PI",
            "kpi_label": "LLM",
            "kpi_sub": "defense",
            "action": "ALLOW-LIST PROMPTS + AUDIT LOGS",
        },
        {
            "tag": "RAG SECURITY",
            "theme": "amber",
            "visual": "data_exfil",
            "headline": "RAG Pipeline Poisoning",
            "subheadline": "RAG pipeline ingestion-time data poisoning defenses for retrieval stores",
            "kpi_value": "RAG",
            "kpi_label": "POISON",
            "kpi_sub": "filter",
        },
        {
            "tag": "MCP THREAT",
            "theme": "blue",
            "visual": "supply_chain_pipe",
            "headline": "MCP Tool Poisoning",
            "subheadline": "Model Context Protocol tool-poisoning and Pickle supply chain attacks",
            "kpi_value": "MCP",
            "kpi_label": "TOOL",
            "kpi_sub": "poison",
        },
    ),
    (
        "2026-03-07",
        "Tech_Security_Weekly_Digest_Android_Zero_Day_DevSecOps",
        "Weekly digest 2026-03-07: Qualcomm CVE-2026-21385 zero-day, CISA KEV update, ransomware",
        {
            "tag": "QC 0-DAY",
            "theme": "red",
            "visual": "cve_chain",
            "headline": "Qualcomm 0-Day Active",
            "subheadline": "Qualcomm chipset zero-day CVE-2026-21385 exploited against Android handsets",
            "kpi_value": "QCC",
            "kpi_label": "21385",
            "kpi_sub": "active",
            "action": "FORCE OEM PATCH + HARDEN MDM",
        },
        {
            "tag": "CISA KEV",
            "theme": "amber",
            "visual": "cve_chain",
            "headline": "CVE-2026-22719 in KEV",
            "subheadline": "CVE-2026-22719 added to CISA Known Exploited Vulnerabilities catalog",
            "kpi_value": "KEV",
            "kpi_label": "22719",
            "kpi_sub": "CISA",
        },
        {
            "tag": "RANSOMWARE",
            "theme": "blue",
            "visual": "ransomware_lock",
            "headline": "Ransomware DevSecOps",
            "subheadline": "Ransomware threats target build-pipeline secrets and CI runner tokens",
            "kpi_value": "CI",
            "kpi_label": "TOKEN",
            "kpi_sub": "theft",
        },
    ),
    (
        "2026-03-08",
        "Tech_Security_Weekly_Digest_AI_Security",
        "Weekly digest 2026-03-08: OpenAI Codex 1.2M commits, USDC $1.8T volume, AI agent patches",
        {
            "tag": "AI CODEX",
            "theme": "red",
            "visual": "ai_agent_funnel",
            "headline": "OpenAI Codex Security",
            "subheadline": "OpenAI Codex security review across 1.2 million enterprise code commits",
            "kpi_value": "1.2M",
            "kpi_label": "COMMITS",
            "kpi_sub": "Codex",
            "action": "TRIAGE AI-FLAGGED FINDINGS",
        },
        {
            "tag": "USDC SCALE",
            "theme": "amber",
            "visual": "data_exfil",
            "headline": "USDC Stablecoin Surge",
            "subheadline": "USDC stablecoin transfer volume passes 1.8 trillion dollar threshold",
            "kpi_value": "1.8T",
            "kpi_label": "USDC",
            "kpi_sub": "volume",
        },
        {
            "tag": "CLOUD PATCH",
            "theme": "blue",
            "visual": "container_escape",
            "headline": "Cloud Agent Patches",
            "subheadline": "AI agent vendors ship coordinated cloud patches across managed offerings",
            "kpi_value": "PCH",
            "kpi_label": "CLOUD",
            "kpi_sub": "agent",
        },
    ),
    (
        "2026-03-09",
        "Tech_Security_Weekly_Digest_AI_Security_Go_Bitcoin",
        "Weekly digest 2026-03-09: Krebs prompt-injection deep-dive, CLARITY Act, DNS exfil",
        {
            "tag": "KREBS PI",
            "theme": "red",
            "visual": "ai_agent_funnel",
            "headline": "Krebs Prompt Injection",
            "subheadline": "Krebs on Security deep-dive on prompt injection and over-broad agent scopes",
            "kpi_value": "PI",
            "kpi_label": "AGENT",
            "kpi_sub": "scope",
            "action": "TIGHTEN AGENT TOOL SCOPES",
        },
        {
            "tag": "CLARITY ACT",
            "theme": "amber",
            "visual": "hub_spoke",
            "headline": "CLARITY Act SEC vs CFTC",
            "subheadline": "CLARITY Act crypto bill clarifies SEC and CFTC jurisdictional split",
            "kpi_value": "CLR",
            "kpi_label": "ACT",
            "kpi_sub": "SEC",
        },
        {
            "tag": "DNS EXFIL",
            "theme": "blue",
            "visual": "data_exfil",
            "headline": "Go-Based DNS Exfil",
            "subheadline": "Go-compiled DNS tunneling tool grows footprint in active intrusions",
            "kpi_value": "Go",
            "kpi_label": "DNS",
            "kpi_sub": "exfil",
        },
    ),
    (
        "2026-03-10",
        "Tech_Security_Weekly_Digest_AI_Malware_Security_Data",
        "Weekly digest 2026-03-10: UNC4899 NK actor AirDrop trojan, Qualcomm 0-day chain, BYOVD",
        {
            "tag": "UNC4899 NK",
            "theme": "red",
            "visual": "data_exfil",
            "headline": "UNC4899 AirDrop Trojan",
            "subheadline": "UNC4899 North Korea actor distributes trojan via AirDrop social engineering",
            "kpi_value": "NK",
            "kpi_label": "UNC",
            "kpi_sub": "4899",
            "action": "DISABLE AIRDROP DEFAULT-ON + ALERT",
        },
        {
            "tag": "QC 0-DAY",
            "theme": "amber",
            "visual": "cve_chain",
            "headline": "Qualcomm iOS Chain",
            "subheadline": "Qualcomm zero-day chains with iOS exploit kit for full-device takeover",
            "kpi_value": "iOS",
            "kpi_label": "CHAIN",
            "kpi_sub": "QC 0d",
        },
        {
            "tag": "BYOVD EDR",
            "theme": "blue",
            "visual": "code_injection",
            "headline": "BYOVD Driver Reuse",
            "subheadline": "Adversaries reuse signed vulnerable drivers to disable EDR runtime hooks",
            "kpi_value": "BYO",
            "kpi_label": "VD",
            "kpi_sub": "EDR off",
        },
    ),
    (
        "2026-03-11",
        "Tech_Security_Weekly_Digest_AI_Agent_Data_Malware",
        "Weekly digest 2026-03-11: Cloudflare attack-surface intel, blockchain wallet ATO, patches",
        {
            "tag": "CF ASI",
            "theme": "red",
            "visual": "hub_spoke",
            "headline": "Cloudflare Attack Surface",
            "subheadline": "Cloudflare attack-surface intelligence flags internet-exposed legacy services",
            "kpi_value": "ASI",
            "kpi_label": "CF",
            "kpi_sub": "expose",
            "action": "RESTRICT EDGE + ROTATE SECRETS",
        },
        {
            "tag": "WALLET ATO",
            "theme": "amber",
            "visual": "data_exfil",
            "headline": "Blockchain Wallet Theft",
            "subheadline": "Targeted account takeover campaigns drain exchange and self-custody wallets",
            "kpi_value": "ATO",
            "kpi_label": "WAL",
            "kpi_sub": "drain",
        },
        {
            "tag": "PATCH PRIORITY",
            "theme": "blue",
            "visual": "cve_chain",
            "headline": "K8s Patch Priority",
            "subheadline": "Kubernetes patch priority guidance highlights kubelet and ingress paths",
            "kpi_value": "PCH",
            "kpi_label": "K8s",
            "kpi_sub": "prio",
        },
    ),
    (
        "2026-03-12",
        "Tech_Security_Weekly_Digest_AI_Malware_AWS_Patch",
        "Weekly digest 2026-03-12: BYOVD EDR campaigns, vertical AI rollout, SBOM patch posture",
        {
            "tag": "BYOVD EDR",
            "theme": "red",
            "visual": "code_injection",
            "headline": "BYOVD Disables EDR",
            "subheadline": "Active BYOVD campaigns disable EDR sensors via signed driver abuse",
            "kpi_value": "EDR",
            "kpi_label": "OFF",
            "kpi_sub": "BYOVD",
            "action": "BLOCK DRIVERS VIA ATTACK-SURFACE",
        },
        {
            "tag": "VERTICAL AI",
            "theme": "amber",
            "visual": "ai_agent_funnel",
            "headline": "Vertical AI Rollouts",
            "subheadline": "Vertical AI adoption opens new third-party data and tool access surfaces",
            "kpi_value": "VAI",
            "kpi_label": "ADOPT",
            "kpi_sub": "scope",
        },
        {
            "tag": "SBOM",
            "theme": "blue",
            "visual": "supply_chain_pipe",
            "headline": "SBOM Patch Posture",
            "subheadline": "SBOM-driven patch posture surfaces hidden transitive dependency risk",
            "kpi_value": "SBM",
            "kpi_label": "DEP",
            "kpi_sub": "trans",
        },
    ),
    (
        "2026-03-15",
        "Tech_Security_Weekly_Digest_AWS_AI_Bitcoin",
        "Weekly digest 2026-03-15: GlassWorm Open VSX 72 extensions, prompt injection, DNS exfil",
        {
            "tag": "OPEN VSX",
            "theme": "red",
            "visual": "supply_chain_pipe",
            "headline": "GlassWorm Open VSX",
            "subheadline": "GlassWorm campaign backdoors 72 Open VSX extensions hitting VS Code forks",
            "kpi_value": "72",
            "kpi_label": "EXT",
            "kpi_sub": "Open VSX",
            "action": "UNINSTALL FLAGGED EXT + ROTATE PAT",
        },
        {
            "tag": "PROMPT INJECT",
            "theme": "amber",
            "visual": "ai_agent_funnel",
            "headline": "AI Agent Prompt Injection",
            "subheadline": "AI agent vulnerabilities surface new prompt injection delivery vectors",
            "kpi_value": "PI",
            "kpi_label": "AGENT",
            "kpi_sub": "exec",
        },
        {
            "tag": "DNS EXFIL",
            "theme": "blue",
            "visual": "data_exfil",
            "headline": "DNS Exfil Campaigns",
            "subheadline": "DNS-based data exfiltration tooling adopted across cloud intrusion cases",
            "kpi_value": "DNS",
            "kpi_label": "EXF",
            "kpi_sub": "cloud",
        },
    ),
    (
        "2026-03-30",
        "March_2026_Security_Digest_Monthly_Index",
        "March 2026 security digest monthly index - weekly summaries and trends",
        {
            "tag": "MONTH BRIEF",
            "theme": "red",
            "visual": "hub_spoke",
            "headline": "March 2026 Brief",
            "subheadline": "March monthly index aggregates weekly digests across CVE, cloud, AI, ICS",
            "kpi_value": "MAR",
            "kpi_label": "INDEX",
            "kpi_sub": "weekly",
            "action": "REVIEW MONTHLY KEV + IR DRILLS",
        },
        {
            "tag": "TOP CVE",
            "theme": "amber",
            "visual": "cve_chain",
            "headline": "Top CVE Highlights",
            "subheadline": "March top-CVE list - Cisco FMC, Qualcomm 0-day, Apple WebKit, CVE-20122",
            "kpi_value": "CVE",
            "kpi_label": "TOP",
            "kpi_sub": "month",
        },
        {
            "tag": "AI THREATS",
            "theme": "blue",
            "visual": "ai_agent_funnel",
            "headline": "AI Threat Roundup",
            "subheadline": "AI agent threats and supply-chain campaigns dominated March 2026 incidents",
            "kpi_value": "AI",
            "kpi_label": "AGENT",
            "kpi_sub": "month",
        },
    ),
]


def emit() -> None:
    for date, slug, title, hero, tr, br in SPECS:
        # add index labels
        hero = {**hero, "index": "01"}
        tr = {**tr, "index": "02"}
        br = {**br, "index": "03"}
        year, month, day = date.split("-")
        block = {
            "date": date,
            "slug": slug,
            "date_str": f"{year}.{month}.{day}",
            "post_title": title,
            "url": f"https://tech.2twodragon.com/posts/{year}/{month}/{day}/{slug}/",
            "hero": hero,
            "top_right": tr,
            "bottom_right": br,
        }
        target = OUT / f"{date}-{slug}.yml"
        with target.open("w") as f:
            yaml.safe_dump(block, f, sort_keys=False, default_flow_style=False, allow_unicode=False, width=120)
        print(f"[ok] {target.name}")


if __name__ == "__main__":
    emit()
