#!/usr/bin/env python3
"""CI/pre-commit wiring guard for the digest STRUCTURE gate's --ratchet mode.

check_digest_structure.py enforces digest structural invariants (contiguous
'## N.' numbering, no body H1, a single checklist surface). The legacy corpus
(~125 posts as of 2026-07-31) carries pre-existing defects awaiting a staged
backfill campaign, so both wires run the gate with --ratchet: only violations
that are NEW vs the base revision fail, while regressions still break the build.

Two failure directions this guard protects against:

1. The gate is dropped entirely  -> structural invariants stop being enforced.
2. --ratchet is dropped          -> the gate reverts to file-scoped and blocks
   every unrelated improvement to a legacy post (the exact breakage that
   stalled Phase 2b; see notes/digest-proper-noun-policy.md §4).

If the gate is intentionally moved/renamed, or the backfill completes and the
ratchet is genuinely no longer needed, update this guard in the same PR and say
why.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SCRIPT = "scripts/check_digest_structure.py"
HOOK = REPO / ".githooks" / "pre-commit"
# .githooks/pre-commit is GENERATED by install-hooks.sh (heredoc). Editing only
# the generated file is silently reverted on the next install run, so the
# canonical source must carry the flag too.
INSTALL = REPO / "scripts" / "install-hooks.sh"
CI = REPO / ".github" / "workflows" / "svg-lint.yml"


def _noncomment(text: str) -> str:
    """Drop comment lines so a commented-out invocation never counts as wired."""
    return "\n".join(ln for ln in text.splitlines() if not ln.lstrip().startswith("#"))


# The hook invokes it as: python3 "$REPO_ROOT/scripts/...py" --staged --ratchet
# so allow an optional closing quote before the flags.
_HOOK_RE = re.compile(rf"{re.escape(SCRIPT)}\"?\s+--staged\s+--ratchet")
# CI invokes it as: python3 scripts/...py --changed "$BASE" --ratchet
_CI_RE = re.compile(
    rf"{re.escape(SCRIPT)}\s+--changed\s+\"?\$?\{{?\w+\}}?\"?\s+--ratchet"
)


def test_script_exists():
    assert (REPO / SCRIPT).is_file(), f"{SCRIPT} missing (moved/renamed?)"


def test_ratchet_flag_still_supported():
    src = (REPO / SCRIPT).read_text(encoding="utf-8")
    assert '"--ratchet"' in src, (
        f"{SCRIPT} no longer defines --ratchet, but the pre-commit hook and "
        "svg-lint CI both pass it. They would fail with an argparse error."
    )


def test_wired_into_active_pre_commit_hook_with_ratchet():
    body = _noncomment(HOOK.read_text(encoding="utf-8"))
    assert _HOOK_RE.search(body), (
        "The active .githooks/pre-commit no longer invokes "
        f"'{SCRIPT} --staged --ratchet'. Either the structure gate was dropped "
        "(invariants unenforced locally) or --ratchet was dropped (the gate now "
        "blocks unrelated improvements to legacy digest posts)."
    )


def test_install_hooks_source_also_carries_ratchet():
    """The generated hook is only as good as its generator (githooks hooksPath gotcha)."""
    body = _noncomment(INSTALL.read_text(encoding="utf-8"))
    assert _HOOK_RE.search(body), (
        "scripts/install-hooks.sh — the canonical source that generates "
        ".githooks/pre-commit — no longer emits "
        f"'{SCRIPT} --staged --ratchet'. The generated hook would be reverted "
        "to the un-ratcheted gate on the next install-hooks.sh run."
    )


def test_wired_into_svg_lint_ci_with_ratchet():
    body = _noncomment(CI.read_text(encoding="utf-8"))
    assert _CI_RE.search(body), (
        f"svg-lint CI no longer invokes '{SCRIPT} --changed <BASE> --ratchet'. "
        "Either the structure gate was dropped from CI or --ratchet was dropped, "
        "which would fail PRs on pre-existing legacy defects they did not cause."
    )


def test_ci_gate_stays_diff_scoped_not_all():
    """--all over the corpus would fail on the legacy backlog by design."""
    body = _noncomment(CI.read_text(encoding="utf-8"))
    assert f"{SCRIPT} --all" not in body, (
        f"svg-lint CI must not run '{SCRIPT} --all' — the legacy corpus has "
        "known pre-existing defects and would fail every build."
    )
