#!/usr/bin/env python3
"""Seed L20 specs for 2025 batch G (Sep-Dec, 15 posts)."""
from pathlib import Path
import yaml

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "_data" / "l20_covers"

SPECS = [
    ("2025-09-10", "npm_Large-scale_Security_20",
     "npm ecosystem mass breach: 18 packages, 2B weekly downloads, supply chain",
     {"tag":"NPM BREACH","theme":"red","visual":"supply_chain_pipe","headline":"18 Packages Compromised",
      "subheadline":"npm registry mass compromise hits 18 packages with 2B weekly downloads",
      "kpi_value":"18","kpi_label":"PKG","kpi_sub":"npm",
      "action":"AUDIT DEPS + LOCK VERSION"},
     {"tag":"DEBUG/CHALK","theme":"amber","visual":"data_exfil","headline":"debug + chalk + lodash",
      "subheadline":"Core packages debug chalk lodash compromised in coordinated attack",
      "kpi_value":"2B","kpi_label":"DLs","kpi_sub":"wk"},
     {"tag":"RECOVERY","theme":"blue","visual":"cve_chain","headline":"Emergency Recovery",
      "subheadline":"Emergency rollback procedure plus supply chain hardening checklist",
      "kpi_value":"REC","kpi_label":"PROC","kpi_sub":"emerg"}),

    ("2025-09-16", "AWS_reInforce_2025_Cloud_Security_and_Future",
     "AWS re:Inforce 2025: Zero Trust, AI threats, GuardDuty extensions, Security Hub",
     {"tag":"re:INFORCE","theme":"red","visual":"hub_spoke","headline":"AWS re:Inforce 2025",
      "subheadline":"AWS re:Inforce 2025 highlights cloud security service announcements",
      "kpi_value":"AWS","kpi_label":"2025","kpi_sub":"conf",
      "action":"PILOT NEW FEATURES Q4"},
     {"tag":"ZERO TRUST","theme":"amber","visual":"cve_chain","headline":"Zero Trust + AI",
      "subheadline":"Zero Trust architecture upgrades with AI-driven threat detection updates",
      "kpi_value":"ZT","kpi_label":"AI","kpi_sub":"new"},
     {"tag":"GUARDDUTY","theme":"blue","visual":"data_exfil","headline":"GuardDuty + Sec Hub",
      "subheadline":"GuardDuty expansion and Security Hub improvements ship at re:Inforce",
      "kpi_value":"GD","kpi_label":"SH","kpi_sub":"ext"}),

    ("2025-09-17", "NPM_Shai-Hulud_180_Large-scale_Analysis",
     "NPM Shai-Hulud worm: 180 packages, self-replicating supply chain attack",
     {"tag":"SHAI-HULUD","theme":"red","visual":"supply_chain_pipe","headline":"180 Pkg Self-Replicate",
      "subheadline":"NPM Shai-Hulud worm self-replicates across 180-plus packages",
      "kpi_value":"180","kpi_label":"PKG","kpi_sub":"worm",
      "action":"FREEZE INSTALL + AUDIT 2FA"},
     {"tag":"WORM","theme":"amber","visual":"code_injection","headline":"Self-Replication Mech",
      "subheadline":"Self-replication mechanism propagates via maintainer credentials",
      "kpi_value":"WORM","kpi_label":"NPM","kpi_sub":"prop"},
     {"tag":"SBOM + 2FA","theme":"blue","visual":"cve_chain","headline":"SBOM + 2FA Required",
      "subheadline":"SBOM generation and mandatory 2FA for npm maintainers as defense",
      "kpi_value":"SBM","kpi_label":"2FA","kpi_sub":"npm"}),

    ("2025-10-02", "Karpenter_v153_Node_Integration_Due_to_Large-scale_Incident_Analysis_and_Resolution",
     "Karpenter v1.5.3 incident: aggressive node consolidation, PDB, EKS stability",
     {"tag":"KARPENTER","theme":"red","visual":"container_escape","headline":"v1.5.3 Aggressive Consolidate",
      "subheadline":"Karpenter v1.5.3 aggressive node consolidation triggers cluster outage",
      "kpi_value":"1.5.3","kpi_label":"KARP","kpi_sub":"out",
      "action":"PIN VERSION + ADD PDB"},
     {"tag":"PDB","theme":"amber","visual":"cve_chain","headline":"PodDisruptionBudget Fix",
      "subheadline":"PodDisruptionBudget enforcement contains uncontrolled node draining",
      "kpi_value":"PDB","kpi_label":"K8s","kpi_sub":"fix"},
     {"tag":"EKS","theme":"blue","visual":"hub_spoke","headline":"EKS Stability Patterns",
      "subheadline":"EKS cluster stability patterns and Karpenter operational guidance",
      "kpi_value":"EKS","kpi_label":"OPS","kpi_sub":"stab"}),

    ("2025-10-03", "AWSin_Database_Access_Gateway_Build_NLB_Security_Group_Complete_Guide",
     "AWS DB access gateway: NLB + Security Group Zero Trust, Terraform automation",
     {"tag":"DB GATEWAY","theme":"red","visual":"hub_spoke","headline":"NLB + SG Gateway",
      "subheadline":"Network Load Balancer plus Security Group Zero Trust database gateway",
      "kpi_value":"NLB","kpi_label":"SG","kpi_sub":"DB",
      "action":"DEPLOY GATEWAY + AUDIT FLOWS"},
     {"tag":"ZERO TRUST","theme":"amber","visual":"cve_chain","headline":"Zero Trust Access",
      "subheadline":"Zero Trust database access control with minimum-privilege SG policies",
      "kpi_value":"ZT","kpi_label":"DB","kpi_sub":"acc"},
     {"tag":"TERRAFORM","theme":"blue","visual":"supply_chain_pipe","headline":"Terraform Automation",
      "subheadline":"Terraform infrastructure automation for repeatable gateway deployment",
      "kpi_value":"TF","kpi_label":"IaC","kpi_sub":"auto"}),

    ("2025-10-31", "AI_Secretary_Security_Hole_For_Enterprise_AI_Service_Security_Guide",
     "Enterprise AI security: Shadow AI, deepfakes, Rogue Agents, governance",
     {"tag":"SHADOW AI","theme":"red","visual":"ai_agent_funnel","headline":"Shadow AI Expansion",
      "subheadline":"Shadow AI proliferation creates new enterprise data exfiltration channels",
      "kpi_value":"SDW","kpi_label":"AI","kpi_sub":"ent",
      "action":"INVENTORY AI + POLICY"},
     {"tag":"DEEPFAKE","theme":"amber","visual":"data_exfil","headline":"Deepfake Fraud",
      "subheadline":"Deepfake-driven fraud campaigns target finance and HR verification flows",
      "kpi_value":"DPF","kpi_label":"AI","kpi_sub":"fraud"},
     {"tag":"ROGUE AGENT","theme":"blue","visual":"code_injection","headline":"Rogue AI Agents",
      "subheadline":"Rogue AI agents bypass policy and require governance framework",
      "kpi_value":"RGE","kpi_label":"AI","kpi_sub":"gov"}),

    ("2025-11-04", "Zscaler_Complete_Guide_SSL_AI_Complete",
     "Zscaler guide: SSL inspection, sandbox ATP, Zero Trust web, ZTNA 2.0",
     {"tag":"SSL INSPECT","theme":"red","visual":"data_exfil","headline":"SSL Inline Inspection",
      "subheadline":"Zscaler SSL inline inspection unblocks visibility into encrypted traffic",
      "kpi_value":"SSL","kpi_label":"INSP","kpi_sub":"zs",
      "action":"ENABLE INSPECT + EXEMPT BANK"},
     {"tag":"SANDBOX","theme":"amber","visual":"code_injection","headline":"Sandbox + ATP",
      "subheadline":"Sandbox ATP analyzes suspicious files before delivery to endpoints",
      "kpi_value":"ATP","kpi_label":"SBX","kpi_sub":"mal"},
     {"tag":"ZTNA 2.0","theme":"blue","visual":"hub_spoke","headline":"ZTNA 2.0 Adoption",
      "subheadline":"ZTNA 2.0 Zero Trust web architecture rollout with category policies",
      "kpi_value":"ZTNA","kpi_label":"2.0","kpi_sub":"web"}),

    ("2025-11-19", "Post-Mortem_2025_11_18_Cloudflare_Global_Incident_Response_Log_what_Learned",
     "Postmortem 2025-11-18: Cloudflare global outage, multi-CDN failover, SRE",
     {"tag":"CF OUTAGE","theme":"red","visual":"hub_spoke","headline":"CF Global Outage 11-18",
      "subheadline":"Cloudflare global outage on November 18 disrupts edge routing worldwide",
      "kpi_value":"11-18","kpi_label":"CF","kpi_sub":"out",
      "action":"ENABLE MULTI-CDN FAILOVER"},
     {"tag":"MULTI-CDN","theme":"amber","visual":"supply_chain_pipe","headline":"Multi-CDN Strategy",
      "subheadline":"Multi-CDN failover strategy with automated DNS-based switching",
      "kpi_value":"CDN","kpi_label":"FAIL","kpi_sub":"over"},
     {"tag":"SRE","theme":"blue","visual":"cve_chain","headline":"SRE Resilience Lessons",
      "subheadline":"SRE infrastructure resilience design lessons learned from the incident",
      "kpi_value":"SRE","kpi_label":"RES","kpi_sub":"des"}),

    ("2025-11-21", "Cloud_Security_8Batch_OT_Guide_DevSecOpsFrom_FinOpsTo_Practical_Talent_Leap",
     "Cloud Security 8 OT: 9-week curriculum, DevSecOps FinOps, AI trends",
     {"tag":"8TH BATCH OT","theme":"red","visual":"hub_spoke","headline":"8th Batch Orientation",
      "subheadline":"8th batch orientation introduces the nine-week security curriculum",
      "kpi_value":"9W","kpi_label":"CURR","kpi_sub":"8th",
      "action":"REGISTER + CONFIRM TRACK"},
     {"tag":"DSO + FINOPS","theme":"amber","visual":"supply_chain_pipe","headline":"DevSecOps + FinOps",
      "subheadline":"DevSecOps and FinOps practical skills roadmap for cloud security teams",
      "kpi_value":"DSO","kpi_label":"FIN","kpi_sub":"OPS"},
     {"tag":"AI TREND","theme":"blue","visual":"ai_agent_funnel","headline":"2025 AI Security",
      "subheadline":"2025 AI security trends shape course direction and career outcomes",
      "kpi_value":"AI","kpi_label":"2025","kpi_sub":"sec"}),

    ("2025-11-26", "Cloud_Security_8Batch_1Week_Infrastructure_EssenceFrom_Security_FutureTo",
     "Cloud Security 8/1: cloud infrastructure essence, AI threats, Zero Trust, PQC",
     {"tag":"INFRA ESSENCE","theme":"red","visual":"hub_spoke","headline":"Cloud Infra Essence",
      "subheadline":"Cloud infrastructure foundational concepts and security implications",
      "kpi_value":"INF","kpi_label":"CORE","kpi_sub":"cloud",
      "action":"MAP WORKLOADS + BASELINE"},
     {"tag":"AI THREAT","theme":"amber","visual":"ai_agent_funnel","headline":"AI Security Threats",
      "subheadline":"AI security threats and response strategy across enterprise workloads",
      "kpi_value":"AI","kpi_label":"THR","kpi_sub":"ent"},
     {"tag":"PQC","theme":"blue","visual":"cve_chain","headline":"Post-Quantum Crypto",
      "subheadline":"Post-quantum cryptography and Zero Trust design principles intro",
      "kpi_value":"PQC","kpi_label":"FUT","kpi_sub":"crypto"}),

    ("2025-12-05", "Cloud_Security_8Batch_2Week_AWS_Security_Architecture_Core_VPCFrom_GuardDutyTo_Complete_Conquer",
     "Cloud Security 8/2: VPC design, IAM least-priv, S3 policy, GuardDuty, re:Invent",
     {"tag":"VPC DESIGN","theme":"red","visual":"hub_spoke","headline":"VPC Security Design",
      "subheadline":"VPC security design with subnet flow log and routing best practices",
      "kpi_value":"VPC","kpi_label":"AWS","kpi_sub":"net",
      "action":"AUDIT VPC + ENABLE FLOW LOGS"},
     {"tag":"IAM","theme":"amber","visual":"cve_chain","headline":"IAM Least Privilege",
      "subheadline":"IAM least-privilege patterns plus S3 bucket policy enforcement",
      "kpi_value":"IAM","kpi_label":"S3","kpi_sub":"min"},
     {"tag":"GUARDDUTY","theme":"blue","visual":"data_exfil","headline":"GuardDuty + re:Invent",
      "subheadline":"GuardDuty threat detection plus re:Invent 2025 new security launches",
      "kpi_value":"GD","kpi_label":"AWS","kpi_sub":"new"}),

    ("2025-12-12", "Cloud_Security_8Batch_3Week_AWS_FinOps_ArchitectureFrom_ISMS-P_Security_AuditTo_Complete_Strategy",
     "Cloud Security 8/3: FinOps trends, Cost Explorer, Trusted Advisor, ISMS-P audit",
     {"tag":"FINOPS 2025","theme":"red","visual":"data_exfil","headline":"FinOps + Cost Explorer",
      "subheadline":"FinOps 2025 trends with AWS Cost Explorer and Trusted Advisor tooling",
      "kpi_value":"FIN","kpi_label":"OPS","kpi_sub":"AWS",
      "action":"REVIEW BUDGETS + ALERTS"},
     {"tag":"ISMS-P","theme":"amber","visual":"hub_spoke","headline":"ISMS-P Audit",
      "subheadline":"ISMS-P certification audit response strategy for cloud environments",
      "kpi_value":"ISMS","kpi_label":"P","kpi_sub":"AUD"},
     {"tag":"COMPLY","theme":"blue","visual":"cve_chain","headline":"Cost + Compliance",
      "subheadline":"Cost optimization and security compliance achieved together in practice",
      "kpi_value":"COST","kpi_label":"CMP","kpi_sub":"join"}),

    ("2025-12-17", "12_Conference_Review_AWSKRUG_OWASP_Datadog_Preview_See_2025_AIand_Security_Coexistence",
     "Dec conferences: AWSKRUG, OWASP, Datadog, 2025 AI x security coexistence",
     {"tag":"AWSKRUG","theme":"red","visual":"hub_spoke","headline":"AWSKRUG + OWASP",
      "subheadline":"AWSKRUG and OWASP seminars surface 2025 AI and security trends",
      "kpi_value":"AWSK","kpi_label":"OWSP","kpi_sub":"conf",
      "action":"FOLLOW UP NEW STANDARDS"},
     {"tag":"DATADOG","theme":"amber","visual":"data_exfil","headline":"Datadog Observability",
      "subheadline":"Datadog observability and LLM security findings from the December summit",
      "kpi_value":"DD","kpi_label":"OBS","kpi_sub":"LLM"},
     {"tag":"ZT STANDARD","theme":"blue","visual":"cve_chain","headline":"Zero Trust Standards",
      "subheadline":"Zero Trust standardization momentum across vendors and frameworks",
      "kpi_value":"ZT","kpi_label":"STD","kpi_sub":"2025"}),

    ("2025-12-19", "Cloud_Security_8Batch_4Week_Integration_Security_Vulnerability_Inspection_and_ISMS-P_Certification_Response",
     "Cloud Security 8/4: integrated vuln scan automation, ISMS-P audit, DSO governance",
     {"tag":"INTEG SCAN","theme":"red","visual":"cve_chain","headline":"Integrated Vuln Scan",
      "subheadline":"Integrated security vulnerability inspection automation framework",
      "kpi_value":"INT","kpi_label":"VULN","kpi_sub":"auto",
      "action":"SCHEDULE + WIRE TO SIEM"},
     {"tag":"ISMS-P","theme":"amber","visual":"hub_spoke","headline":"ISMS-P Audit Response",
      "subheadline":"ISMS-P certification audit preparation and operational response steps",
      "kpi_value":"ISMS","kpi_label":"P","kpi_sub":"aud"},
     {"tag":"GOVERN","theme":"blue","visual":"supply_chain_pipe","headline":"DSO Governance",
      "subheadline":"DevSecOps governance applied to continuous compliance management",
      "kpi_value":"DSO","kpi_label":"GOV","kpi_sub":"cmp"}),

    ("2025-12-24", "Cloud_Security_Course_8Batch_5Week_AWS_Control_TowerSCP_Based_Governance_and_Datadog_SIEM_Cloudflare_Security",
     "Cloud Security 8/5: Control Tower SCP, Datadog SIEM, Cloudflare web sec",
     {"tag":"CTL TOWER","theme":"red","visual":"hub_spoke","headline":"Control Tower + SCP",
      "subheadline":"AWS Control Tower SCP-based multi-account governance and landing zone",
      "kpi_value":"CT","kpi_label":"SCP","kpi_sub":"AWS",
      "action":"DEFINE SCP + ENFORCE LZ"},
     {"tag":"DATADOG SIEM","theme":"amber","visual":"data_exfil","headline":"Datadog SIEM",
      "subheadline":"Datadog SIEM unified security monitoring across cloud and on-prem signals",
      "kpi_value":"DD","kpi_label":"SIEM","kpi_sub":"unif"},
     {"tag":"CLOUDFLARE","theme":"blue","visual":"cve_chain","headline":"Cloudflare Web Sec",
      "subheadline":"Cloudflare web security hardening complements Datadog SIEM coverage",
      "kpi_value":"CF","kpi_label":"WEB","kpi_sub":"sec"}),
]

def emit():
    for date, slug, title, hero, tr, br in SPECS:
        hero = {**hero, "index": "01"}
        tr = {**tr, "index": "02"}
        br = {**br, "index": "03"}
        year, month, day = date.split("-")
        block = {
            "date": date, "slug": slug,
            "date_str": f"{year}.{month}.{day}", "post_title": title,
            "url": f"https://tech.2twodragon.com/posts/{year}/{month}/{day}/{slug}/",
            "hero": hero, "top_right": tr, "bottom_right": br,
        }
        target = (Path(__file__).resolve().parent.parent / "_data" / "l20_covers" / f"{date}-{slug}.yml")
        with target.open("w") as f:
            yaml.safe_dump(block, f, sort_keys=False, default_flow_style=False, allow_unicode=False, width=120)
        print(f"[ok] {target.name}")

if __name__ == "__main__":
    emit()
