#!/usr/bin/env python3
"""Gate: an excerpt must not promise content the post does not contain.

What this catches
-----------------
``excerpt:`` is what the listing pages, the RSS feed, the search index and the
Google result show before a reader opens anything. Digest excerpts are
generated by ``scripts/seo_diversify_excerpts.py``, which used to pick the
closing sentence from a hash of the FILENAME with no reference to the body.

Measured 2026-09-10 over the 217 non-rollup digests. The first diagnosis asked
only whether the promised NOUN appears anywhere in the body:

    "공격 경로·영향 평가…를 단계별로 다룹니다"    1 of 42 posts mention 공격 경로
    "보안 운영센터(SOC)…"                        8 of 42 mention SOC
    "SBOM 기반 의존성 패치…"                    21 of 50 mention SBOM
    "…IoC 정리표를 포함합니다"                   23 of 47 mention IoC at all
    "…실무 체크리스트를 함께 제공합니다"         35 of 35  <- kept

That is 129 posts. This gate then reported **150**, and the difference is not a
contradiction: the predicates here are stricter than "the word appears". The
IoC closer promises a 정리표, so it requires a table row that actually lists
IoCs (6 of 47, not 23); the SBOM closer names EDR too, so it requires both.
Each predicate is written to match what its sentence actually claims.

The last row is why this gate is keyed to specific sentences rather than to a
general "does the excerpt overclaim" heuristic: the boilerplate was not
uniformly false, and a heuristic that flagged all of it would have been wrong
about a seventh of the corpus. The defect was the hash, not the phrasing.

Scope and direction
-------------------
Only the closing sentences declared in ``seo_diversify_excerpts.CLOSERS`` are
checked, and each is checked against its own declared ``requires`` predicate —
the same predicate the generator now uses to choose it. An excerpt that ends in
anything else is hand-written and is left alone; this gate has no opinion about
prose it did not generate.

That makes it allow-by-default, which is the right direction here. The
alternative — inferring promises from arbitrary excerpt text — is the
``check_digest_untranslated`` trap this repo has already paid for: a heuristic
that is correct next door is usually wrong here. If a new closer is added to
the generator it is covered automatically, because both sides read one list.

Usage
-----
::

    python3 scripts/check_excerpt_promises.py --all
    python3 scripts/check_excerpt_promises.py --staged
    python3 scripts/check_excerpt_promises.py _posts/2026-09-10-Foo.md

Exit codes: 0 clean, 1 violations found, 2 bad invocation.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from seo_diversify_excerpts import (  # noqa: E402
    CLOSERS,
    _extract_existing_excerpt,
    _split_front_matter,
    current_closer_index,
)


def _display(path: Path) -> str:
    """Repo-relative when possible, absolute otherwise.

    ``Path.relative_to`` raises for anything outside the repo, and the only
    caller was on the violation-printing path — so a file passed by absolute
    path from elsewhere (a tmp dir, a worktree) crashed the gate exactly when
    it had something to report, and passed silently when it did not.
    """
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def violation(path: Path) -> str | None:
    """Return a human-readable violation for ``path``, or ``None`` if clean."""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        return f"unreadable: {exc}"

    fm, body = _split_front_matter(text)
    if fm is None:
        return None
    excerpt = _extract_existing_excerpt(fm.raw)
    if not excerpt:
        return None

    idx = current_closer_index(excerpt)
    if idx is None:
        return None  # hand-written ending — not a generated promise

    closer = CLOSERS[idx]
    if closer.requires(body):
        return None
    return (
        f"excerpt promises {closer.text.strip()!r}\n    but the body lacks {closer.why}"
    )


def _staged_posts() -> list[Path]:
    out = subprocess.run(
        ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM", "-z"],
        capture_output=True,
        text=True,
        check=True,
        cwd=ROOT,
    ).stdout
    return [
        ROOT / n
        for n in out.split("\0")
        if n.startswith("_posts/") and n.endswith(".md")
    ]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("paths", nargs="*", type=Path)
    ap.add_argument("--all", action="store_true", help="every post in _posts/")
    ap.add_argument("--staged", action="store_true", help="staged posts only")
    args = ap.parse_args(argv)

    if args.all:
        targets = sorted((ROOT / "_posts").glob("*.md"))
    elif args.staged:
        targets = _staged_posts()
    elif args.paths:
        targets = [p if p.is_absolute() else ROOT / p for p in args.paths]
    else:
        ap.error("pass --all, --staged, or one or more paths")
        return 2

    missing = [p for p in targets if not p.is_file()]
    if missing:
        for p in missing:
            print(f"❌ {p}: not found", file=sys.stderr)
        return 1

    if not targets:
        print("✅ excerpt promises: no posts to check")
        return 0

    bad = [(p, v) for p in targets if (v := violation(p)) is not None]
    for path, why in bad:
        print(f"❌ {_display(path)}: {why}")

    if bad:
        print(
            f"\n{len(bad)} of {len(targets)} post(s) promise content they do not "
            "contain.\nRepair with:\n"
            "    python3 scripts/seo_diversify_excerpts.py --apply --repair-promises",
            file=sys.stderr,
        )
        return 1

    print(f"✅ excerpt promises: {len(targets)} post(s) clean")
    return 0


if __name__ == "__main__":
    sys.exit(main())
