#!/usr/bin/env python3
"""actionlint informational-tier ratchet — the count may fall, never rise.

Why this exists
---------------
The blocking gate in `.github/workflows/action-pin-check.yml` enforces every
native actionlint rule plus shellcheck findings at `warning` and above. It
deliberately excludes `info` and `style`, because on 2026-08-26 the corpus
carried 70 of them (65 info / 5 style) across 12 workflows. Gating on that
would have forced an unrelated 70-site rewrite or, far more likely, produced a
muted job — which is how this repo previously ended up with gates that had
never once been right.

Excluding a tier and printing its count is honest, but it is not a control:
nothing stopped the 70 from becoming 90. This script is the missing half. The
two steps are exact complements, so every finding actionlint emits is now
covered by one of them:

    blocking gate ... native rules (all severities) + SC warning/error
    this ratchet .... SC info + SC style

Why a (file, code, severity) key rather than the message text
-------------------------------------------------------------
Measured 2026-08-27 on `.github/workflows/lighthouse.yml`, control-first:

    control  .../lighthouse.yml:58:9: ... SC2086:info:2:25: Double quote ...
    mutated  .../lighthouse.yml:59:9: ... SC2086:info:2:25: Double quote ...

The mutation was a single irrelevant comment line prepended to the file. The
shell script is byte-identical and the finding is the same finding, yet a
string-multiset comparison reads it as "1 pre-existing disappeared, 1 new
appeared" and fails. That is precisely the false block this repo already paid
for once in `check_digest_structure.py --ratchet` (PR #492), in a different
disguise: there the message embedded body *text*, here it embeds *positions*.
Generalised: before ratcheting on a violation message, check what it embeds,
and key the comparison on something that cannot move for unrelated reasons.

`(file, code, severity)` is position-independent and still catches what matters:
a newly unquoted variable in a file raises that file's SC2086 count. A
fix-one-add-one wash inside a single file nets zero and passes, which is the
same tolerance the digest ratchet has and an accepted limit of counting.

Why two-sided
-------------
An increase is a regression. A *decrease* also fails, with an explicit
`--update` instruction, because that is what makes this a ratchet rather than a
ceiling: if fixing three findings did not tighten the baseline, the three slots
stay open for someone to fill later. Deleting a workflow trips the same path,
which is correct — a baseline should not cite a file that no longer exists.

Why shellcheck absence is fatal
-------------------------------
actionlint runs shellcheck as a subprocess and, when the binary is missing,
emits zero SC findings and exits cleanly. The ratchet would then see 70 -> 0,
report "baseline stale", and a plausible reaction is to run `--update` and
commit a baseline of zeros — after which the gate enforces nothing forever.
So a missing shellcheck is exit 2 (environment error), never a finding count.

Usage
-----
    # CI / local check
    python3 scripts/check_actionlint_ratchet.py

    # After fixing findings, tighten the baseline
    python3 scripts/check_actionlint_ratchet.py --update

    # Parse a captured run instead of invoking actionlint
    python3 scripts/check_actionlint_ratchet.py --from-file out.txt

Exit codes: 0 clean, 1 ratchet violation, 2 usage/environment error.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_BASELINE = REPO_ROOT / "scripts" / "actionlint_ratchet_baseline.txt"

# Exactly the tiers the blocking gate excludes. Keep in lockstep with the
# `-ignore` patterns in .github/workflows/action-pin-check.yml: a tier present
# in neither place is a tier nothing enforces.
RATCHETED_SEVERITIES = ("info", "style")

# A finding line, e.g.
#   .github/workflows/jekyll.yml:45:9: shellcheck reported issue in this
#   script: SC2086:info:13:33: Double quote to prevent ... [shellcheck]
# Anchored on a .yml/.yaml path so the indented source-snippet lines actionlint
# interleaves ("  45 | run: |", "     | ^~~~") can never match.
_FINDING_RE = re.compile(
    r"^(?P<file>\S+\.ya?ml):\d+:\d+:.*?\b(?P<code>SC\d+):(?P<severity>[a-z]+):"
)

_BASELINE_LINE_RE = re.compile(
    r"^(?P<file>\S+)\s+(?P<code>SC\d+)\s+(?P<severity>[a-z]+)\s+(?P<count>\d+)$"
)

BASELINE_HEADER = """\
# scripts/actionlint_ratchet_baseline.txt
# Grandfathered actionlint informational findings (SC info + SC style) — the
# tiers the blocking gate in .github/workflows/action-pin-check.yml excludes.
#
# Auto-generated by: python3 scripts/check_actionlint_ratchet.py --update
#
# Format: <workflow-path> <SC-code> <severity> <count>
#
# The key is (file, code, severity) and NOT the finding text, because the text
# embeds line:col positions that move whenever anything above them is edited.
# See the module docstring of check_actionlint_ratchet.py for the measurement.
#
# The ratchet is two-sided: a higher count is a regression, a lower count means
# this file is stale and must be regenerated with --update so the slots you
# freed cannot be silently refilled.
"""

Key = tuple[str, str, str]  # (file, code, severity)


def parse_findings(output: str) -> Counter[Key]:
    """Count ratcheted findings in actionlint output, keyed by (file, code, severity)."""
    counts: Counter[Key] = Counter()
    for line in output.splitlines():
        match = _FINDING_RE.match(line)
        if not match:
            continue
        severity = match.group("severity")
        if severity not in RATCHETED_SEVERITIES:
            continue
        counts[(match.group("file"), match.group("code"), severity)] += 1
    return counts


# actionlint's exit codes, confirmed empirically against v1.7.12 on 2026-08-27:
#   0  no problems      1  problems reported
#   2  command-line error                 3  fatal (e.g. "no project was found
#                                            in any parent directories")
# Only 0 and 1 are results. 2 and 3 print a diagnostic and no findings, which
# parses to zero and would be reported as "baseline stale" — the same shape as
# the missing-shellcheck hazard below, and how a probe harness of this very
# script produced a bogus control (exit 3, read as 0 findings) before the code
# was checked.
_ACTIONLINT_RESULT_CODES = (0, 1)


def run_actionlint() -> str:
    """Invoke actionlint at the repo root and return its combined output."""
    if shutil.which("actionlint") is None:
        raise EnvironmentError(
            "actionlint is not on PATH. This check cannot run without it; "
            "install it or pass --from-file with a captured run."
        )
    if shutil.which("shellcheck") is None:
        raise EnvironmentError(
            "shellcheck is not on PATH. actionlint would then emit zero SC "
            "findings and exit cleanly, so this ratchet would compare the real "
            "baseline against an empty result and report it as stale. Refusing "
            "to produce a count that means nothing — install shellcheck."
        )
    proc = subprocess.run(
        ["actionlint"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode not in _ACTIONLINT_RESULT_CODES:
        raise EnvironmentError(
            f"actionlint exited {proc.returncode} (not a result code); its output "
            f"carries no findings and must not be counted as zero:\n"
            f"{(proc.stderr or proc.stdout).strip()}"
        )
    return proc.stdout + proc.stderr


def load_baseline(path: Path) -> Counter[Key]:
    counts: Counter[Key] = Counter()
    if not path.is_file():
        raise EnvironmentError(
            f"baseline not found: {path}. Generate it with --update."
        )
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        match = _BASELINE_LINE_RE.match(line)
        if not match:
            raise EnvironmentError(
                f"{path}:{lineno}: malformed baseline entry: {raw!r}"
            )
        key = (match.group("file"), match.group("code"), match.group("severity"))
        counts[key] += int(match.group("count"))
    return counts


def render_baseline(counts: Counter[Key]) -> str:
    lines = [BASELINE_HEADER]
    total = sum(counts.values())
    lines.append(f"# Total grandfathered findings: {total}\n")
    for (path, code, severity), count in sorted(counts.items()):
        lines.append(f"{path} {code} {severity} {count}\n")
    return "".join(lines)


def compare(
    current: Counter[Key], baseline: Counter[Key]
) -> tuple[list[str], list[str]]:
    """Return (regressions, stale_entries) as human-readable lines."""
    regressions: list[str] = []
    stale: list[str] = []
    for key in sorted(set(current) | set(baseline)):
        path, code, severity = key
        now, before = current[key], baseline[key]
        if now > before:
            regressions.append(
                f"  {path}  {code}:{severity}  {before} -> {now}  (+{now - before})"
            )
        elif now < before:
            stale.append(
                f"  {path}  {code}:{severity}  {before} -> {now}  (-{before - now})"
            )
    return regressions, stale


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--baseline",
        type=Path,
        default=DEFAULT_BASELINE,
        help="baseline file (default: scripts/actionlint_ratchet_baseline.txt)",
    )
    parser.add_argument(
        "--from-file",
        type=Path,
        help="parse captured actionlint output instead of invoking actionlint",
    )
    parser.add_argument(
        "--update",
        action="store_true",
        help="rewrite the baseline from the current findings",
    )
    args = parser.parse_args(argv)

    try:
        if args.from_file is not None:
            output = args.from_file.read_text(encoding="utf-8")
        else:
            output = run_actionlint()
    except (EnvironmentError, OSError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    current = parse_findings(output)
    total = sum(current.values())

    if args.update:
        args.baseline.write_text(render_baseline(current), encoding="utf-8")
        print(
            f"Wrote {args.baseline} — {total} findings across {len(current)} (file, code, severity) keys."
        )
        return 0

    try:
        baseline = load_baseline(args.baseline)
    except EnvironmentError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    regressions, stale = compare(current, baseline)
    baseline_total = sum(baseline.values())

    # Always report the standing debt. "We exclude info" must not decay into
    # "nobody knows how many there are".
    print(
        f"actionlint ratchet ({'+'.join(RATCHETED_SEVERITIES)}): "
        f"{total} findings now, {baseline_total} in baseline."
    )

    if regressions:
        print(
            "\nNEW informational findings — the ratchet only turns one way:",
            file=sys.stderr,
        )
        print("\n".join(regressions), file=sys.stderr)
        print(
            "\nQuote the variable (or fix the cited shellcheck code) rather than "
            "raising the baseline. If the finding is genuinely unavoidable, say so "
            "in the PR and update the baseline in the same diff.",
            file=sys.stderr,
        )
    if stale:
        print("\nBaseline is stale — fewer findings than recorded:", file=sys.stderr)
        print("\n".join(stale), file=sys.stderr)
        print(
            "\nRun: python3 scripts/check_actionlint_ratchet.py --update\n"
            "Leaving the higher number in place would keep those slots open for "
            "a future regression, which is the whole thing this file prevents.",
            file=sys.stderr,
        )

    return 1 if (regressions or stale) else 0


if __name__ == "__main__":
    sys.exit(main())
