import os
import glob
import re
import random
import textwrap

# Ensure assets/images exists
os.makedirs('assets/images', exist_ok=True)

def get_random_color():
    colors = ['#FFD700', '#FFA500', '#FF6347', '#4682B4', '#32CD32', '#9370DB', '#FF69B4', '#20B2AA']
    return random.choice(colors)

def create_banana_svg(title, filename):
    color = get_random_color()
    # Simple banana path
    banana_path = "M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z"
    # Actually that path looks like a globe (world). Let's use a simpler banana shape or just a placeholder icon if I can't draw a perfect banana from memory.
    # Let's try a crescent shape for a banana.
    banana_path = "M15.5 5.5C15.5 5.5 19 8 19 12C19 18 14 22 8 22C11 22 14 20 15.5 17C17 14 15.5 5.5 15.5 5.5Z" # Very rough banana
    
    # Let's use a generic abstract background with a text overlay
    
    # Wrap title
    wrapper = textwrap.TextWrapper(width=30)
    title_lines = wrapper.wrap(title)
    text_elements = ""
    y_offset = 120
    for line in title_lines:
        text_elements += f'<text x="50%" y="{y_offset}" dominant-baseline="middle" text-anchor="middle" font-family="Arial, sans-serif" font-size="24" fill="white" font-weight="bold">{line}</text>\n'
        y_offset += 30

    svg_content = f'''<svg xmlns="http://www.w3.org/2000/svg" width="800" height="400" viewBox="0 0 800 400">
  <defs>
    <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:{color};stop-opacity:1" />
      <stop offset="100%" style="stop-color:#333;stop-opacity:1" />
    </linearGradient>
  </defs>
  <rect width="800" height="400" fill="url(#grad1)" />
  
  <!-- Nano Banana Icon Placeholder -->
  <g transform="translate(350, 40) scale(4)">
     <path fill="#FFFF00" d="M4.336 2.015c3.273-2.16 11.233-1.637 15.65 1.547-.487.352-1.35.53-2.193.38-2.67-.473-5.263-.78-7.734-.913-1.74-.094-3.528.083-5.263.52 4.194 3.197 9.155 4.318 14.545 3.125.875-.194 2.12-.596 2.45-.963.267.362 2.628 3.56 1.815 6.02-3.23 9.773-16.746 8.918-19.897 4.156-1.55-2.342-1.314-10.45 2.812-13.633.26-.2.435-.38.435-.38l-2.62-.24z"/>
  </g>
  
  {text_elements}
  
  <text x="780" y="380" text-anchor="end" font-family="monospace" font-size="14" fill="rgba(255,255,255,0.5)">Generated by Gemini CLI</text>
</svg>'''
    
    with open(filename, 'w') as f:
        f.write(svg_content)

def process_posts():
    posts = glob.glob('_posts/*.md')
    for post_path in posts:
        with open(post_path, 'r') as f:
            content = f.read()
        
        # Parse Front Matter
        if not content.startswith('---'):
            continue
            
        try:
            front_matter_end = content.find('---', 3)
            front_matter = content[3:front_matter_end]
            body = content[front_matter_end+3:]
            
            # Extract title
            title_match = re.search(r'title:\s*"(.*)"', front_matter)
            if not title_match:
                 title_match = re.search(r'title:\s*(.*)', front_matter)
            
            title = title_match.group(1) if title_match else "Untitled"
            
            # Determine new image filename
            basename = os.path.basename(post_path).replace('.md', '')
            image_filename = f'assets/images/{basename}.svg'
            
            # Create SVG
            create_banana_svg(title, image_filename)
            
            # Update Front Matter
            if 'image:' not in front_matter:
                new_front_matter = front_matter.rstrip() + f'\nimage: /{image_filename}\n'
                new_content = f'---{new_front_matter}---{body}'
                
                with open(post_path, 'w') as f:
                    f.write(new_content)
                print(f"Updated {post_path} with image")
            else:
                print(f"Skipping {post_path}, image already exists")
                
        except Exception as e:
            print(f"Error processing {post_path}: {e}")

if __name__ == "__main__":
    process_posts()
