#!/bin/sh
# Install project git hooks into .git/hooks/
# Run once after cloning or when hooks change: bash scripts/install-hooks.sh

set -e
REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_FILE="$REPO_ROOT/.git/hooks/pre-commit"

echo "[install-hooks] Installing pre-commit hook..."

cat > "$HOOK_FILE" << 'HOOK'
#!/bin/sh
# Auto-generated by scripts/install-hooks.sh — do not edit directly.
# Re-run: bash scripts/install-hooks.sh

REPO_ROOT="$(git rev-parse --show-toplevel)"

# 1. HTML entity residue guard — check staged filenames and frontmatter image: fields
python3 "$REPO_ROOT/scripts/check_filename_entities.py" --staged
if [ $? -ne 0 ]; then
  exit 1
fi

# 2. Run pytest when Python scripts change
CHANGED_PY=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^scripts/.*\.py$' || true)
if [ -n "$CHANGED_PY" ]; then
  echo "[pre-commit] Running tests..."
  python3 -m pytest "$REPO_ROOT/scripts/tests/" -x -q 2>&1
  if [ $? -ne 0 ]; then
    echo "[pre-commit] FAILED"
    exit 1
  fi
  echo "[pre-commit] Passed."
fi

# 3. SVG quality gate (size bands — warnings only, does not block)
sh "$REPO_ROOT/scripts/check_svg_precommit.sh"

# 4. SVG XML well-formedness check
echo "[pre-commit] Validating SVG XML well-formedness..."
SVG_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.svg$' || true)
if [ -n "$SVG_FILES" ]; then
  if ! command -v xmllint >/dev/null 2>&1; then
    echo "[pre-commit] WARNING: xmllint not found, skipping SVG XML validation"
  else
    BROKEN=0
    for svg in $SVG_FILES; do
      if [ -f "$svg" ]; then
        if ! xmllint --noout "$svg" 2>/tmp/svg-xmllint-error.$$; then
          echo "[pre-commit] BROKEN SVG: $svg"
          sed -n '1,5p' /tmp/svg-xmllint-error.$$ | sed 's/^/    /'
          BROKEN=$((BROKEN + 1))
        fi
      fi
    done
    rm -f /tmp/svg-xmllint-error.$$
    if [ "$BROKEN" -gt 0 ]; then
      echo ""
      echo "[pre-commit] FAIL: $BROKEN SVG file(s) have XML errors."
      echo "  Most common cause: unescaped & (use &amp;) or < (use &lt;) in text content."
      echo "  To auto-fix: python3 scripts/verify_images_unified.py --svg-validate --svg-fix"
      exit 1
    fi
    echo "[pre-commit] SVG XML validation: OK"
  fi
fi

# 5. SVG compliance linter (placeholder text, accent/category mismatch, missing signature — blocks commit)
STAGED_SVGS=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^assets/images/2026-[^/]+\.svg$' || true)
if [ -n "$STAGED_SVGS" ]; then
  echo "[pre-commit] Running SVG compliance linter..."
  # Convert newline-separated list to space-separated args
  SVG_ARGS=""
  for f in $STAGED_SVGS; do
    SVG_ARGS="$SVG_ARGS $f"
  done
  python3 "$REPO_ROOT/scripts/lint_svg_compliance.py" --files $SVG_ARGS
  if [ $? -ne 0 ]; then
    echo "[pre-commit] SVG compliance violations found. Fix before committing."
    echo "             To bypass (not recommended): git commit --no-verify"
    exit 1
  fi
  echo "[pre-commit] SVG compliance: passed."
fi
HOOK

chmod +x "$HOOK_FILE"
echo "[install-hooks] Done. Hook written to $HOOK_FILE"
