#!/bin/sh
# Install project git hooks into .git/hooks/
# Run once after cloning or when hooks change: bash scripts/install-hooks.sh

set -e
REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_FILE="$REPO_ROOT/.git/hooks/pre-commit"

echo "[install-hooks] Installing pre-commit hook..."

cat > "$HOOK_FILE" << 'HOOK'
#!/bin/sh
# Auto-generated by scripts/install-hooks.sh — do not edit directly.
# Re-run: bash scripts/install-hooks.sh

REPO_ROOT="$(git rev-parse --show-toplevel)"

# 1. HTML entity residue guard — check staged filenames and frontmatter image: fields
python3 "$REPO_ROOT/scripts/check_filename_entities.py" --staged
if [ $? -ne 0 ]; then
  exit 1
fi

# 2. Run pytest when Python scripts change
CHANGED_PY=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^scripts/.*\.py$' || true)
if [ -n "$CHANGED_PY" ]; then
  echo "[pre-commit] Running tests..."
  python3 -m pytest "$REPO_ROOT/scripts/tests/" -x -q 2>&1
  if [ $? -ne 0 ]; then
    echo "[pre-commit] FAILED"
    exit 1
  fi
  echo "[pre-commit] Passed."
fi

# 3. SVG quality gate
sh "$REPO_ROOT/scripts/check_svg_precommit.sh"
HOOK

chmod +x "$HOOK_FILE"
echo "[install-hooks] Done. Hook written to $HOOK_FILE"
